# Generated by Django 5.2.11 on 2026-02-12 10:41

import apps.remedial.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromiseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_no', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('terms_json', models.JSONField(blank=True, default=dict)),
                ('grace_days', models.PositiveSmallIntegerField(default=3)),
                ('default_threshold_days', models.PositiveSmallIntegerField(default=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('compromise_signed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_compromises', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_compromises', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CompromiseScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('due', 'Due'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='due', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_escalation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('compromise_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='remedial.compromiseagreement')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('compromise_agreement', 'seq_no')},
            },
        ),
        migrations.CreateModel(
            name='CompromisePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_no', models.CharField(blank=True, max_length=128)),
                ('compromise_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='remedial.compromiseagreement')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromise_payments', to=settings.AUTH_USER_MODEL)),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='remedial.compromisescheduleitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('sent_to', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rule_code', 'entity_type', 'entity_id'], name='remedial_no_rule_co_d6c290_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('days_before', models.IntegerField(blank=True, null=True)),
                ('days_after', models.IntegerField(blank=True, null=True)),
                ('email_to_role', models.CharField(blank=True, max_length=64)),
                ('template_code', models.CharField(max_length=64)),
                ('email_to_specific', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemedialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_account_no', models.CharField(max_length=64, unique=True)),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_id_ref', models.CharField(blank=True, max_length=64)),
                ('outstanding_balance_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stage', models.CharField(choices=[('pre_legal', 'Pre-legal'), ('compromise', 'Compromise'), ('legal', 'Legal'), ('foreclosure', 'Foreclosure'), ('dacion', 'Dacion'), ('write_off', 'Write-off'), ('closed', 'Closed')], default='pre_legal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='active', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_remedial_accounts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('foreclosure', 'Foreclosure'), ('dacion', 'Dacion')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_recovery_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant')),
                ('remedial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='remedial.remedialaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('small_claims', 'Small Claims'), ('regular', 'Regular Collection')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('active', 'Active'), ('decided', 'Decided'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('case_number', models.CharField(blank=True, max_length=64)),
                ('court_name', models.CharField(max_length=255)),
                ('court_branch', models.CharField(max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('assigned_counsel', models.CharField(blank=True, max_length=255)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_legal_cases', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant')),
                ('remedial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='remedial.remedialaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compromiseagreement',
            name='remedial_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromise_agreements', to='remedial.remedialaccount'),
        ),
        migrations.CreateModel(
            name='RemedialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('remedial_account', 'Remedial Account'), ('compromise_agreement', 'Compromise Agreement'), ('legal_case', 'Legal Case'), ('recovery_action', 'Recovery Action'), ('write_off', 'Write-off')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('doc_type', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to=apps.remedial.models.document_upload_path)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_confidential', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_remedial_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remedial_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recommended', 'Recommended'), ('board_approved', 'Board Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('recommended_at', models.DateTimeField(blank=True, null=True)),
                ('board_resolution_ref', models.CharField(blank=True, max_length=255)),
                ('board_decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommended_write_offs', to=settings.AUTH_USER_MODEL)),
                ('remedial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_requests', to='remedial.remedialaccount')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hearing_date', models.DateField()),
                ('hearing_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('reset', 'Reset'), ('cancelled', 'Cancelled')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='remedial.legalcase')),
            ],
            options={
                'indexes': [models.Index(fields=['hearing_date', 'status'], name='remedial_co_hearing_a7999e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(max_length=50)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('overdue', 'Overdue')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='remedial.recoveryaction')),
            ],
            options={
                'indexes': [models.Index(fields=['target_date', 'status'], name='remedial_re_target__80b896_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='remedialaccount',
            index=models.Index(fields=['stage', 'status'], name='remedial_re_stage_e14862_idx'),
        ),
        migrations.AddIndex(
            model_name='remedialaccount',
            index=models.Index(fields=['assigned_officer', 'stage'], name='remedial_re_assigne_8b0b3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='compromiseagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['approved', 'active', 'defaulted'])), fields=('remedial_account',), name='unique_active_compromise_per_account'),
        ),
        migrations.AddConstraint(
            model_name='compromiseagreement',
            constraint=models.UniqueConstraint(fields=('remedial_account', 'agreement_no'), name='unique_compromise_per_account'),
        ),
        migrations.AddIndex(
            model_name='remedialdocument',
            index=models.Index(fields=['entity_type', 'entity_id'], name='remedial_re_entity__87ecfc_idx'),
        ),
    ]
