# Generated by Django 5.2.11 on 2026-02-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedial', '0001_initial_models'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisepayment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='compromisescheduleitem',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='courthearing',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='recoverymilestone',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='remedialdocument',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='compromiseagreement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='recoveryaction',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='remedialaccount',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='writeoffrequest',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_objects', to='tenancy.tenant'),
        ),
    ]
