# Generated by Django 5.2.11 on 2026-02-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedial', '0002_compromisepayment_tenant_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromiseagreement',
            old_name='terms_json',
            new_name='terms',
        ),
        migrations.AlterField(
            model_name='compromiseagreement',
            name='terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
